name: "CodeQL: Start proxy"
description: "[Experimental] Start HTTP proxy server. This action is for internal GitHub used only and will change without notice."
author: "GitHub"
inputs:
  registry_secrets:
    description: The URLs and credentials of package registries
    required: false
    default: "[]"
  registries_credentials:
    description: Base64 encoded JSON configuration for the URLs and credentials of the package registries
    required: false
  proxy_password:
    required: false
    description: The password of the proxy
  token:
    description: GitHub token to use for authenticating with this instance of GitHub, used to upload debug artifacts.
    default: ${{ github.token }}
    required: false
outputs:
  proxy_host:
    description: The IP address of the proxy
  proxy_port:
    description: The port of the proxy
  proxy_ca_certificate:
    description: The proxy's internal CA certificate in PEM format
  proxy_urls:
    description: The URLs of the configured registries, as a JSON array.
runs:
  using: node16
  main: "../lib/start-proxy-action.js"
  post: "../lib/start-proxy-action-post.js"
